### ISSUE TITLE
File names for Jekyll posts

### ISSUE THREAD

**Issue by jeremyboggs** [Purdom/Purdom.github.io#1]
There are a few files in the `_posts` directory that aren't showing up on home page. It seems be becasue these files use underscores instead of dashes. [Jekyll requires dashes for the file names](http://jekyllrb.com/docs/posts/#creating-post-files), for better or worse.

**Comment by waynegraham** [comment]
Something like this should fix it:

``` bash
find _posts/ -depth -name "* *" -execdir rename 's/-/_/g' "{}" \;
```
