### ISSUE TITLE
Markdown inside block of HTML isn't parsed.

### ISSUE THREAD

**Issue by jeremyboggs** [Purdom/Purdom.github.io#2]
The Nafisi post has post content inside a div, but Jekyll isn't parsing the Markdown into paragraphs and lists and such. Removing that wrapper div does the trick. Imagine you can add that wrapper, with the necessary `vocab` attribute, using a layout that references some YAML frontmatter in the post itself.

**Comment by erochest** [comment]
Yeah, that feature has already been added to the pluging.
